# Generated by Django 4.2.7 on 2023-11-30 19:22

import core.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('profissao', models.CharField(max_length=100, verbose_name='Profissão')),
                ('email', models.CharField(max_length=100, verbose_name='E-Mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumbs': {'crop': True, 'height': 400, 'width': 400}}, verbose_name='Imagem')),
                ('facebook', models.CharField(default='#', max_length=100, verbose_name='Facebook')),
                ('twitter', models.CharField(default='#', max_length=100, verbose_name='Twitter')),
                ('instagram', models.CharField(default='#', max_length=100, verbose_name='Instagram')),
                ('linkeddin', models.CharField(default='#', max_length=100, verbose_name='LinkedIn')),
                ('github', models.CharField(default='#', max_length=100, verbose_name='GitHub')),
                ('codepen', models.CharField(default='#', max_length=100, verbose_name='Codepen')),
            ],
            options={
                'verbose_name': 'DadoPessoal',
                'verbose_name_plural': 'DadosPessoais',
            },
        ),
        migrations.CreateModel(
            name='Educacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('instituicao', models.CharField(max_length=100, verbose_name='Instituição')),
                ('curso', models.CharField(max_length=200, verbose_name='Curso')),
                ('anoinicio', models.CharField(max_length=4, verbose_name='Ano de Início')),
                ('anotermino', models.CharField(max_length=4, verbose_name='Ano de Termino')),
            ],
            options={
                'verbose_name': 'Educacao',
                'verbose_name_plural': 'Educações',
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('empresa', models.CharField(max_length=100, verbose_name='Empresa')),
                ('anoinicio', models.CharField(max_length=4, verbose_name='Ano de Início')),
                ('anotermino', models.CharField(max_length=4, verbose_name='Ano de Término')),
                ('resumo', models.TextField(max_length=500, verbose_name='Resumo de Atividades')),
                ('tecnologia1', models.CharField(max_length=100, verbose_name='Tecnologia Utilizada 01')),
                ('tecnologia2', models.CharField(max_length=100, verbose_name='Tecnologia Utilizada 02')),
                ('tecnologia3', models.CharField(max_length=100, verbose_name='Tecnologia Utilizada 03')),
                ('tecnologia4', models.CharField(max_length=100, verbose_name='Tecnologia Utilizada 04')),
                ('tecnologia5', models.CharField(max_length=100, verbose_name='Tecnologia Utilizada 05')),
                ('tecnologia6', models.CharField(max_length=100, verbose_name='Tecnologia Utilizada 06')),
                ('tecnologia7', models.CharField(max_length=100, verbose_name='Tecnologia Utilizada 07')),
                ('tecnologia8', models.CharField(max_length=100, verbose_name='Tecnologia Utilizada 08')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
            },
        ),
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('interesse', models.CharField(max_length=100, verbose_name='Interesse')),
            ],
            options={
                'verbose_name': 'Interesse',
                'verbose_name_plural': 'Interesses',
            },
        ),
        migrations.CreateModel(
            name='Lingua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('lingua', models.CharField(max_length=100, verbose_name='Língua')),
                ('nivel', models.CharField(choices=[('nativo', 'Nativo'), ('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], max_length=15, verbose_name='Nível')),
            ],
            options={
                'verbose_name': 'Lingua',
                'verbose_name_plural': 'Linguas',
            },
        ),
        migrations.CreateModel(
            name='Sumario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('sumario', models.TextField(max_length=1000, verbose_name='Bio')),
            ],
            options={
                'verbose_name': 'Sumario',
                'verbose_name_plural': 'Sumarios',
            },
        ),
        migrations.CreateModel(
            name='TipoSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('tiposkill', models.CharField(max_length=100, verbose_name='Tipo de Skill')),
            ],
            options={
                'verbose_name': 'TipoSkill',
                'verbose_name_plural': 'TiposSkill',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Skill')),
                ('porcentagem', models.CharField(max_length=3, verbose_name='Porcentagem')),
                ('tiposkill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tiposkill', verbose_name='TipoSkill')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
    ]
